/**
 * Session-start project context injection.
 * Auto-detects and injects project context files (AGENTS.md, codemap.md)
 * into the first user message, providing the orchestrator with project
 * architecture knowledge at session start.
 *
 * Also injects Serena MCP onboarding check instructions.
 *
 * Uses experimental.chat.messages.transform so it doesn't show in UI.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const CONTEXT_FILES = [
  'AGENTS.md', // OpenCode's native project context file
  'codemap.md', // Generated by the cartography skill
];

const SERENA_SESSION_PROMPT = `<serena_onboarding>
IMPORTANT: Before starting work, call serena_check_onboarding_performed.
If onboarding has not been done for this project, call serena_onboarding and follow its instructions.
This ensures Serena MCP has the project context needed for accurate code intelligence.
</serena_onboarding>`;

interface MessageInfo {
  role: string;
  agent?: string;
}

interface MessagePart {
  type: string;
  text?: string;
  [key: string]: unknown;
}

interface MessageWithParts {
  info: MessageInfo;
  parts: MessagePart[];
}

export function createProjectContextHook(projectDir: string) {
  return {
    'experimental.chat.messages.transform': async (
      _input: Record<string, never>,
      output: { messages: MessageWithParts[] },
    ): Promise<void> => {
      const { messages } = output;

      // Only inject on the first user message (session start)
      const userMessages = messages.filter((m) => m.info.role === 'user');
      if (userMessages.length !== 1) return;

      // Only inject for orchestrator
      const msg = userMessages[0];
      if (msg.info.agent && msg.info.agent !== 'orchestrator') return;

      // Find and inject project context
      let contextContent = '';
      for (const filename of CONTEXT_FILES) {
        const filepath = join(projectDir, filename);
        if (existsSync(filepath)) {
          try {
            const content = readFileSync(filepath, 'utf-8');
            contextContent += `\n<project_context source="${filename}">\n${content}\n</project_context>\n`;
          } catch {
            // skip unreadable files
          }
        }
      }

      // Always inject Serena onboarding check
      contextContent += `\n${SERENA_SESSION_PROMPT}\n`;

      const textPartIndex = msg.parts.findIndex(
        (p) => p.type === 'text' && p.text !== undefined,
      );
      if (textPartIndex === -1) return;

      const originalText = msg.parts[textPartIndex].text ?? '';
      msg.parts[textPartIndex].text =
        `${contextContent}\n\n---\n\n${originalText}`;
    },
  };
}
